# Generated by Django 5.0.3 on 2024-03-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image pic'),
        ),
    ]
