# Generated by Django 4.2.11 on 2024-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_record_record_id_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='winner',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
