# Generated by Django 4.2.11 on 2024-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_result_player_alter_result_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='duaration',
            field=models.PositiveIntegerField(),
        ),
    ]
